### ISSUE TITLE
Charmed MicroK8s 1.28

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/charm-microk8s#108]
#### Summary

Branch the 1.28 code!

#### Information

- **MicroK8s version**: 1.28

- **Owner**: @ktsakalozos 

- **Reviewer**: @neoaggelos 

- **PR**: https://github.com/canonical/charm-microk8s/pull/109

#### Actions

The steps are to be followed in-order, each task must be completed by the person specified in **bold**. Do not perform any steps unless all previous ones have been signed-off. The **Reviewer** closes the issue once all steps are complete.

- [x] **Owner**: Add the assignee and reviewer as assignees to the GitHub issue
- [x] **Owner**: Ensure that you are part of the ["microk8s developers" team](https://launchpad.net/~microk8s-dev)
- [x] **Owner**: Request a new `1.xx` CharmHub track for the `microk8s` charm following the [charmstore instructions](https://juju.is/docs/sdk/create-a-track-for-your-charm). 
https://discourse.charmhub.io/t/request-for-track-guardrails-and-1-28-track-for-the-microk8s-charm/11775
- [x] **Owner**: Create `release-1.xx` branch from latest `master`
  - `git checkout master`
  - `git pull`
  - `git checkout -b release-1.xx`
  - `git push origin release-1.xx`
- [x] **Reviewer**: Ensure `release-1.xx` branch is based on latest changes on master at the time of the release cut.
- [x] **Owner**: Create PR to initialize `release-1.xx` branch:
  - [x] Update branch from `master` to `release-1.xx` in [.github/workflows/cla-check.yml](../workflows/cla-check.yml)
  - [x] Update branch from `master` to `release-1.xx` in [.github/workflows/python.yml](../workflows/python.yml)
  - [x] Update branch from `master` to `release-1.xx` in [.github/workflows/test.yml](../workflows/test.yml)
  - [x] Update `cancel-in-progress` from `refs/heads/master` to `refs/heads/release-1.xx` in [.github/workflows/test.yml](../workflows/test.yml)
  - [x] Update `SNAP_CHANNEL` to `1.xx` in [src/charm_config.py](../../src/charm_config.py)
  - [x] Update `*_CHANNEL` in [tests/integration/config.py](../../tests/integration/config.py). Kubernetes charms should use `1.xx/edge`, others should use `edge` unless there has been a breaking change.
  - [x] `git commit -m 'Release 1.xx'`
  - [x] Create PR with the changes and request review from **Reviewer**. Make sure to update the issue `Information` section with a link to the PR.
- [x] **Reviewer**: Review and merge PR to initialize branch.
- [x] **Owner**: Create launchpad builders for `release-1.xx`
  - [x] Go to https://code.launchpad.net/~microk8s-dev/charm-microk8s/+git/charm-microk8s and do **Import now** to pick up all latest changes.
  - [x] Under **Branches**, select `release-1.xx`, then **Create charm recipe**
  - [x] Set **Charm recipe name** to `microk8s-1.xx`
  - [x] Enable **Automatically build when branch changes**
  - [x] Enable **Automatically upload to store**
  - [x] Set **Registered store name** to `microk8s`
  - [x] In **Store Channels**, set **Track** to `1.xx` and **Risk** to `edge`. Leave **Branch** empty
  - [x] Click **Create charm recipe** at the bottom of the page. You will be asked to authenticate with CharmHub so that LaunchPad can automatically push the charm on each build.
- [x] **Reviewer**: Ensure charm recipe for `release-1.xx` is created
  - List of recipes https://code.launchpad.net/~microk8s-dev/charm-microk8s/+git/charm-microk8s/+charm-recipes

#### After release

**Owner** follows up with the **Reviewer** and team about things to improve around the process.

**Comment by neoaggelos** [comment]
Awesome! We now have builds in `1.28/edge`:

```
$ juju info microk8s | grep 1.28/
  1.28/stable:       --
  1.28/candidate:    --
  1.28/beta:         --
  1.28/edge:         170  2023-09-06  (170)  7MB  armhf  ubuntu@20.04, ubuntu@22.04
```
