### ISSUE TITLE
Wishlist: support for injecting caching registries

### ISSUE THREAD

**Issue by sabaini** [canonical/charm-microk8s#46]
A wishlist item: provide support for injecting caching registries, for instance to avoid hitting rate limiting on upstream registries.

For instance, this could be done by exposing a config option that takes a list of  `<upstream>,<registry-url>;...` 

Setting this to eg. `k8s.gcr.io,http://10.1.1.1:8082;docker.io,http://10.1.1.2:8082` should result in something like the below

```
sudo mkdir -p /var/snap/microk8s/current/args/certs.d/k8s.gcr.io
cat << EOF | sudo tee /var/snap/microk8s/current/args/certs.d/k8s.gcr.io/hosts.toml
server = "http://10.1.1.1:8082"

[host."http://10.1.1.1:8082"]
  capabilities = ["pull", "resolve"]
EOF

sudo mkdir -p /var/snap/microk8s/current/args/certs.d/docker.io
cat << EOF  | sudo tee /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml
server = "http://10.1.1.2:8082"

[host."http://10.1.1.2:8082"]
  capabilities = ["pull", "resolve"]
EOF

sudo microk8s stop
sudo microk8s start
```

**Comment by neoaggelos** [comment]
I have had a branch on this lying around for some time now but have not had the time to revisit and add proper testing coverage. Happy to review a PR if someone can pick it up and work on adding tests.

Here's the branch: https://github.com/canonical/charm-microk8s/compare/master...feat/registry-mirrors Thanks!

**Comment by javacruft** [comment]
@neoaggelos I may just do that - would really speed up our testing

**Comment by neoaggelos** [comment]
This is now implemented, see `containerd_custom_registries` config option.
