### ISSUE TITLE
Charm doesn't honor cluster interface

### ISSUE THREAD

**Issue by vernhart** [canonical/charm-microk8s#57]
When clustering multiple microk8s nodes, the primary node will produce multiple URLs, one for each interface, and the secondary units will attempt to join the cluster with one of these URLs. If reverse DNS for the IP on that interface does not match the hostname of the secondary unit, the join request is rejected. This is a catastrophic failure because the charms don't ever regenerate the joining URLs and will never successfully join, even if reverse DNS is somehow corrected.

In a maas deployment, only one IP will have reverse dns to the node's hostname, the other IPs will have reverse dns something like bond0.111.hostname.domain so we need to be able to predictably select which URL is used for joining the cluster.

One logical option would be to have the charm try all of the provided URLs but the first one that fails will invalidate the token and any subsequent tries, even with different IPs, will fail with token errors.

The charm already has a "cluster" interface. When resolving the relationship between the primary and secondary units, the charm could compare the provided URLs with the cluster interface to make sure the URL used is in the space of the cluster binding, we can predictably determine which URL gets used.

**Comment by neoaggelos** [comment]
This has been fixed in the new MicroK8s charm, where the proper address is used when sharing the join url to the rest of the control plane and worker units.
