### ISSUE TITLE
microk8s app shows active even when microk8s status is not running

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/charm-microk8s#62]
Deployed microk8s charm on juju 3.1/stable. The application came to active state

```
$ juju status -m controller
Model       Controller       Cloud/Region     Version  SLA          Timestamp
controller  sunbeam-default  sunbeam/default  3.1.0    unsupported  11:02:17Z

App         Version  Status  Scale  Charm            Channel      Rev  Exposed  Message
controller           active      1  juju-controller  3.1/stable    14  no       
microk8s             active      1  microk8s         latest/edge   29  no       

Unit           Workload  Agent  Machine  Public address  Ports      Message
controller/0*  active    idle   0        10.5.2.129                 
microk8s/0*    active    idle   0        10.5.2.129      16443/tcp  

Machine  State    Address     Inst id  Base          AZ  Message
0        started  10.5.2.129  manual:  ubuntu@22.04      Manually provisioned machine
```

But microk8s status is not running

```
$ microk8s status
microk8s is not running. Use microk8s inspect for a deeper inspection.
```

The reason for microk8s not running is due to no proper proxy setting for downloading images which is fine.
The expected result is juju status should show ERROR for microk8s application

**Comment by neoaggelos** [comment]
Hi @hammerstefan

Can you share an inspection report from the cluster? Is this just the Calico pods not coming up due to proxy issues or something else?

The MicroK8s charm deploys the MicroK8s machinery, and a successful state is one where the Kubernetes cluster has been deployed.

**Comment by hemanthnakkina** [comment]
@neoaggelos I do not have the environment anymore but can get you inspection report early next week.
Yes the calico pods are not coming up as container images are not getting downloaded.

So the workload (microk8s) is not ready to use and so the charm should update application workload status to ERROR instead of active.

**Comment by neoaggelos** [comment]
@hemanthnakkina this has been fixed in the new MicroK8s charm version where the units go into ready status iff when the Kubelet goes into ready state.

Closing this issue, please re-open if it occurs.
