### ISSUE TITLE
coredns config in charm should default to empty

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/charm-microk8s#66]
Deployed charm-microk8s with addon dns enabled with dns server 10.254.160.2
 
``
$ juju config microk8s addons
dns:10.245.160.2 hostpath-storage: metallb:10.20.21.10-10.20.21.20
``

However the coredns still shows 8.8.8.8,8.8.4.4 as forwarder.
```
$ microk8s.kubectl -n kube-system get cm coredns -o yaml
apiVersion: v1
data:
  Corefile: |
    # This file is managed by Juju. Manual changes may be lost at any time.

    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        log . {
          class error
        }
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 8.8.8.8 8.8.4.4
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
```

Expected the forwarder to be 10.254.160.2.

The problem is because of default config value of coredns which is hardcoded to 8.8.8.8,8.8.8.4.4 as forwarder [1].
If coredns configuration is not updated, microk8s snap could have taken care to update forwarder in coredns configmap [2].

Suggestion is not to have any default value for config coredns_config and leave it to to microk8s to handle unless user specifies coredns_config.

[1] https://github.com/canonical/charm-microk8s/blob/master/config.yaml#L47
[2] https://github.com/canonical/microk8s-core-addons/blob/main/addons/dns/coredns.yaml#L35

**Comment by neoaggelos** [comment]
Proposal sounds like a good compromise, but see my comment on the PR itself.

Also, worth mentioning that starting from MicroK8s 1.26, you should no longer have to specify the upstream nameservers when enabling the DNS addon, MicroK8s will pick them up from the host by default https://github.com/canonical/microk8s-core-addons/pull/111

**Comment by hemanthnakkina** [comment]
I see the problem with microk8s 1.26 as well since the charm default is overriding the coredns configmap set by the microk8s snap. 
So the charm default for coredns_config does not make sense.
