### ISSUE TITLE
wrong containerd_custom_registries

### ISSUE THREAD

**Issue by marosg42** [canonical/charm-microk8s#99]
#### Summary
When using `containerd_custom_registries: '[{ "url": "http://10.245.221.126:5000", "host": "10.245.212.157:5000" }]'` resulting toml file contains

```
server = "http://10.245.221.126:5000"

[host."http://10.245.221.126:5000"]
capabilities = [
    "pull",
    "resolve",
]
```

#### What Should Happen Instead?
It should contain
```
server = "http://10.245.221.126:5000"

[host."http://10.245.212.157:5000"]
capabilities = [
    "pull",
    "resolve",
]
```

charm channel latest/edge

**Comment by neoaggelos** [comment]
As per discussion offline, this is in fact the expected configuration. To configure a `docker.io` mirror, the following config should be used:

```yaml
containerd_custom_registries: '[{"url": "http://10.245.221.126:5000", "host": "docker.io"}]'
````

Closing the issue, please re-open if the above does not succeed. Thanks!
